# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  # - repo: https://github.com/browniebroke/django-codemod
  #   rev: v1.11.3
  #   hooks:
  #     - id: djcodemod
  #       stages: [manual]
  #       args: [
  #         "run",
  #         "--deprecated-in", "1.9",
  #         "--deprecated-in", "1.10",
  #         "--deprecated-in", "1.11",
  #         "--deprecated-in", "2.0",
  #         "--deprecated-in", "2.1",
  #         "--deprecated-in", "2.2",
  #         "--removed-in", "3.0",
  #         "--deprecated-in", "3.0",
  #         "--deprecated-in", "3.1",
  #         "--removed-in", "4.0",
  #       ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.185
    hooks:
      - id: ruff
        alias: autoformat
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        alias: autoformat
        args: [--py310-plus, --py310-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        alias: autoformat
