default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rtts/djhtml
    rev: 'v2.0.0'
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 4
        alias: autoformat
      # - id: djcss
      #   alias: autoformat
      # - id: djjs
      #   alias: autoformat
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
        alias: autoformat
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        alias: autoformat
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.185
    hooks:
      - id: ruff
        alias: autoformat
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        alias: autoformat
