x-common-settings: &common-settings
  build:
    context: .
    dockerfile: ./Dockerfile
    target: release
  depends_on:
    - db
  environment:
    - "ALLOWED_HOSTS=*"
    - "DATABASE_URL=postgres://postgres@db/postgres"
    - "DJANGO_DEBUG=true"
  volumes:
    - .:/src:cache

services:

  db:
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    image: "pgautoupgrade/pgautoupgrade:latest"
    init: true
    volumes:
      - .:/src:cache
      - postgres-data:/var/lib/postgresql/data/

  utility:
    <<: *common-settings

  web:
    <<: *common-settings
    command: ["python", "-m", "manage", "runserver", "0.0.0.0:8000"]
    entrypoint: ["/src/compose-entrypoint.sh"]
    init: true
    ports:
      - "8000:8000"
    tty: true

volumes:
  postgres-data:
