version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: release
    # container_name: {{ project_name }}-app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=on
    ports:
      - "8000:8000"
    volumes:
      - .:/code

volumes:
  postgres_data:
